### ISSUE TITLE
Segmentation Fault 11 when running init.py

### ISSUE THREAD

**Issue by traw1234** [tambetm/minecraft-py#1]
When I run init.py, I get the error `Segmentation Fault 11`. I have tried on my MacBook Pro running macOS 10.12.2 with python 2.7.12 and on my Jetson TX1 running Ubuntu 16.04 and python 2.7.12. The error seems to come from `proc, port = minecraft_py(start)`. On the TX1, the exact error is `Process 'command '/usr/lib/jvm/java-8-openjdk-arm64/bin/java'' finished with non-zero exit value 1`.

**Comment by tambetm** [comment]
Sorry for a long delay. Segmentation fault is a generic error that usually means some kind of binary incompatibility. Are you able to run original Malmo using `launchClient.sh`? Also do you get any errors printed out?

**Comment by traw1234** [comment]
I think that the issue is from Malmo because I get a build error on launchClient.sh. I've submitted an [issue](https://github.com/Microsoft/malmo/issues/431) there so we'll see if that can fix the problem.

**Comment by tambetm** [comment]
Closing this, as it is Malmo issue.
